name: weather_app
description: A weather app built using flutter.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.12.0
  firebase_core: ^2.20.0
  cloud_firestore: ^4.12.1
  flutter_dotenv: ^5.1.0
  geolocator: ^10.1.0
  dio: ^5.3.3
  fluttertoast: ^8.2.2
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
    - assets/svg/
    - .env


